package com.k1.spitter.checkdb;

import java.util.List;

import org.hibernate.Session;
import org.hibernate.SessionFactory;

import com.k1.spitter.entity.Spitter;

public class MethodsUpdate {

	/////////////////////// Update/////////////////////////////
	// (username, password, fullname, email, update_by_email) values
	// ('habuma', 'password', 'Craig Walls', 'craig@habuma.com', false)

	// change name
	public static void spittersUpdateName(SessionFactory factory, int id, String userName) {
		// get current session
		Session session = factory.getCurrentSession();
		// start transaction
		session.beginTransaction();

		// get spitter object from db by id
		Spitter temp = session.get(Spitter.class, id);
		// change name
		temp.setUserName(userName);
		// we need assign autogenerated time stamp to null, because hibernate
		// have some problems with auto change of this field
		temp.setTimestamp(null);

		// force transaction
		session.getTransaction().commit();
	}

	// change fullname
	public static void spittersUpdateFullName(SessionFactory factory, int id, String fullName) {
		// get current session
		Session session = factory.getCurrentSession();
		// start transaction
		session.beginTransaction();

		// get spitter object from db by id
		Spitter temp = session.get(Spitter.class, id);
		// change fullname
		temp.setFullName(fullName);
		// we need assign autogenerated time stamp to null, because hibernate
		// have some problems with auto change of this field
		temp.setTimestamp(null);

		// force transaction
		session.getTransaction().commit();
	}

	// change email
	public static void spittersUpdateEmail(SessionFactory factory, int id, String email) {
		// get current session
		Session session = factory.getCurrentSession();
		// start transaction
		session.beginTransaction();

		// get spitter object from db by id
		Spitter temp = session.get(Spitter.class, id);
		// change email
		temp.setEmail(email);
		// we need assign autogenerated time stamp to null, because hibernate
		// have some problems with auto change of this field
		temp.setTimestamp(null);

		// force transaction
		session.getTransaction().commit();
	}

	// change password
	public static void spittersUpdatePassword(SessionFactory factory, int id, String password) {
		// get current session
		Session session = factory.getCurrentSession();
		// start transaction
		session.beginTransaction();

		// get spitter object from db by id
		Spitter temp = session.get(Spitter.class, id);
		// change password
		temp.setPassword(password);
		// we need assign autogenerated time stamp to null, because hibernate
		// have some problems with auto change of this field
		temp.setTimestamp(null);

		// force transaction
		session.getTransaction().commit();
	}

}
